# Generated by Django 2.2.4 on 2019-10-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app23', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
